#cloud-config
user: user
password: pass
chpasswd:
  expire: False
#package_reboot_if_required: true
package_update: true
package_upgrade: true
packages:
  - git
  - bash
  - binutils-dev
  - bison
  - coreutils
  - diffutils
  - findutils
  - gawk
  - gcc
  - g++
  - grep
  - gzip
  - m4
  - make
  - patch
  - perl
  - python3-dev
  - sed
  - tar
  - texinfo
  - xz-utils
power_state:
  mode: reboot
runcmd:
  - [ln, --symbolic, --force, /bin/bash, /bin/sh]
device_aliases: {lfs_disk: /dev/vdb}
disk_setup:
  lfs_disk:
    layout: true
    overwrite: true
    table_type: mbr
fs_setup:
  - {device: lfs_disk.1, filesystem: ext4, label: lfs}
mounts:
  - [vdisk.1, /mnt/lfs]

